// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS4BWvUr1vVoJokvcDBQH3YJOuHwtSovc',
    appId: '1:977001645690:web:75956f775ee78893c79dc3',
    messagingSenderId: '977001645690',
    projectId: 'samon-ec83b',
    authDomain: 'samon-ec83b.firebaseapp.com',
    storageBucket: 'samon-ec83b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS4BWvUr1vVoJokvcDBQH3YJOuHwtSovc',
    appId: '1:977001645690:android:75956f775ee78893c79dc3',
    messagingSenderId: '977001645690',
    projectId: 'samon-ec83b',
    storageBucket: 'samon-ec83b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS4BWvUr1vVoJokvcDBQH3YJOuHwtSovc',
    appId: '1:977001645690:ios:75956f775ee78893c79dc3',
    messagingSenderId: '977001645690',
    projectId: 'samon-ec83b',
    storageBucket: 'samon-ec83b.firebasestorage.app',
    iosBundleId: 'com.example.projectS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS4BWvUr1vVoJokvcDBQH3YJOuHwtSovc',
    appId: '1:977001645690:macos:75956f775ee78893c79dc3',
    messagingSenderId: '977001645690',
    projectId: 'samon-ec83b',
    storageBucket: 'samon-ec83b.firebasestorage.app',
    iosBundleId: 'com.example.projectS',
  );
} 